//
//  Notifications.swift
//  
//
//  Created by Aaron Brethorst on 10/25/25.
//

import Foundation

/// A collection of notifications generated by the OTPKit framework.
/// Subscribe to them through the NotificationCenter passed to `TripPlanner`
/// and/or `TripPlannerViewModel`.
public struct Notifications {
    public static let itinerariesUpdated = NSNotification.Name("org.onebusaway.otpkit.itinerariesUpdated")
    public static let itineraryPreviewStarted = NSNotification.Name("org.onebusaway.otpkit.itineraryPreviewStarted")
    public static let itineraryPreviewEnded = NSNotification.Name("org.onebusaway.otpkit.itineraryPreviewEnded")
}
