name: OTPKitTests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Show Xcode & list schemes
        run: |
          xcodebuild -version
          xcodebuild -list

      - name: Build & Test OTPKit (Simulator)
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme OTPKit \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            test \
            -enableCodeCoverage YES \
            -resultBundlePath OTPKitTests.xcresult | xcpretty

      - name: Upload xcresult
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OTPKitTests.xcresult
          path: OTPKitTests.xcresult

      # Add PR annotations from the xcresult
      - name: Annotate PR with test results
        if: always()
        uses: kishikawakatsumi/xcresulttool@v1.7.0
        with:
          show-passed-tests: false
          path: OTPKitTests.xcresult
